version: '3'
services:
  php-fpm:
    container_name: phalcon-crawler_php-fpm
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./code:/app
      - ./docker/php-fpm/config/25-psr.ini:/etc/php/7.2/fpm/conf.d/25-psr.ini
      - ./docker/php-fpm/config/30-phalcon.ini:/etc/php/7.2/fpm/conf.d/30-phalcon.ini
      - ./docker/php-fpm/config/25-psr.ini:/etc/php/7.2/cli/conf.d/25-psr.ini
      - ./docker/php-fpm/config/30-phalcon.ini:/etc/php/7.2/cli/conf.d/30-phalcon.ini
      - ./docker/php-fpm/config/www.conf:/etc/php/7.2/fpm/pool.d/www.conf
    ports:
      - "9000:9000"
  nginx:
    container_name: phalcon-crawler_nginx
    build: ./docker/nginx
    volumes:
      - ./code:/app
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"